version: "3.8"

services:
  # Angular Frontend
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./angular-frontend
      target: development

    command: npm run start
    volumes:
      - ./angular-frontend:/todo-api/frontend/src/app
      - /todo-api/frontend/src/app/node_modules

    ports:
      - "4200:4200"

    depends_on:
      - api
  # NestJS Todo Api
  api:
    build:
      dockerfile: Dockerfile
      context: ./todo-api
      target: development

    volumes:
      - ./todo-api:/todo-api/src/app
      - /todo-api/src/app/node_modules/

    # dev mode: npm run start:dev / debuf mode: npm run start:debug
    command: npm run start:dev

    environment:
      DB_URL: postgresql://user:password@todo-db:5432/todo_db
    ports:
      - "5000:4000"

  postgres:
    container_name: todo-db
    image: postgres:15.2-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo_db
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres
    ports:
      - "5432:5432"

  postgres_admin:
    image: dpage/pgadmin4:6.12
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password

    ports:
      - 5050:80

volumes:
  postgres-db:
    driver: local
