version: "3.8"

services:
  # NestJS Todo Api
  api:
    build:
      dockerfile: Dockerfile
      context: ./todo-api
      target: development

    volumes:
      - ./todo-api:/todo-api/src/app
      - /todo-api/src/app/node_modules/

    # dev mode: npm run start:dev / debuf mode: npm run start:debug
    command: npm run start:dev

    environment:
      DB_URL: postgresql://user:password@localhost:5437/todo_db
    ports:
      - 5000:4000

  postgres:
    image: postgres:14.4
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo_db

    ports:
      - 5437:5432

  postgres_admin:
    image: dpage/pgadmin4:6.12
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password

    ports:
      - 5050:80
